# Generated by Django 4.2.3 on 2023-08-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Std',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField()),
                ('Register_number', models.CharField()),
                ('Department', models.CharField()),
                ('Year', models.IntegerField()),
                ('Contact', models.CharField()),
                ('Email_id', models.EmailField(max_length=254)),
                ('Transport', models.CharField()),
                ('Address', models.TextField()),
            ],
        ),
    ]
