# Generated by Django 4.2.3 on 2023-08-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='Year',
            field=models.CharField(),
        ),
    ]
